# Generated by Django 3.1.7 on 2021-03-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.event'),
        ),
    ]
